### ISSUE TITLE
How to Create a New User

### ISSUE THREAD

**Issue by ghost** [yandex-qatools/embedded-services#7]
I would need to add an admin user, but cannot figure out how to create one apart from the one created through constructor

```
        MongoEmbeddedService mongoService = new MongoEmbeddedService(
                "localhost:9992",
                "mobile_registration_test",
                "mongodev",
                "mongodev",
                "localreplica"
        );
```

Would appreciate help.

**Comment by ghost** [comment]
I guess it is 

```
        mongoService.setAdminUsername("mongodev");
        mongoService.setAdminPassword("mongodev");
```

Isn't it?

**Comment by smecsia** [comment]
Yep, that's it.

**Comment by ghost** [comment]
Thank you, just needed to use the correct version of database

```
mongoService.useVersion(Version.Main.LEGACY);
```

I know, know, v3+ is out there. 
Thanks, Ilya, an awesome product you have. Closing this one off.
